default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:231118391815:android:a4e13c20952892c72538a2",
      firebase_cli_token: "1//03ehJkBfwIrdzCgYIARAAGAMSNwF-L9Ir_KDBmlKKxMzfa9Xy805jcqeWLF4vxxfSGjkpbO_cktDcfyCy2o1GAQ2a17YL2ckuu4A",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "mohameekartali@gmail.com",
      release_notes: "First Fastlane Firebase Distribution!"
    )
  end

end
